services:
  postgres:
    image: postgres:17-bookworm
    restart: unless-stopped
    volumes:
      - postgres-vsat:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      # https://hub.docker.com/_/postgres/

    ports:
      - 5432:5432

volumes:
  postgres-vsat:
